context("TerminatorCombo")

test_that("API", {
  t1 = TerminatorEvals$new(2)
  t2 = TerminatorPerfReached$new(c(dummy.cp = 0))

  tt = TerminatorCombo$new(list(t1, t2), any = TRUE)
  pe = TEST_MAKE_INST1(measures = "dummy.cp")
  pe$eval_batch(data.table(cp = 0.2))
  expect_false(t1$is_terminated(pe))
  expect_false(t2$is_terminated(pe))
  expect_false(tt$is_terminated(pe))
  pe$eval_batch(data.table(cp = 0.1))
  expect_true(t1$is_terminated(pe))
  expect_false(t2$is_terminated(pe))
  expect_true(tt$is_terminated(pe))


  tt = TerminatorCombo$new(list(t1, t2), any = FALSE)
  pe = TEST_MAKE_INST1(measures = "dummy.cp")
  pe$eval_batch(data.table(cp = 0.2))
  expect_false(t1$is_terminated(pe))
  expect_false(t2$is_terminated(pe))
  expect_false(tt$is_terminated(pe))
  pe$eval_batch(data.table(cp = 0.1))
  expect_true(t1$is_terminated(pe))
  expect_false(t2$is_terminated(pe))
  expect_false(tt$is_terminated(pe))
  pe$eval_batch(data.table(cp = 0))
  expect_true(t1$is_terminated(pe))
  expect_true(t2$is_terminated(pe))
  expect_true(tt$is_terminated(pe))
})
